maplegrocery/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'maplegrocery'

urlpatterns = [
        path('', views.product_list, name='product_list'),
        # re_path(r'^home/$', views.home, name='home'),
        path('unit_list', views.unit_list, name='unit_list'),
        path('unit/create/', views.unit_new, name='unit_new'),
        path('unit/<int:pk>/edit/', views.unit_edit, name='unit_edit'),
        path('unit/<int:pk>/delete/', views.unit_delete, name='unit_delete'),
        path('product_list', views.product_list, name='product_list'),
        path('product_detail', views.product_detail, name='product_detail'),
        path('product/create/', views.product_new, name='product_new'),
        path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
        path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
        path('category_list', views.category_list, name='category_list'),
        path('category/create/', views.category_new, name='category_new'),
        path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
        path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
        path('order_list', views.order_list, name='order_list'),
        path('order/create/', views.order_create, name='order_create'),
        path('order/<int:pk>/edit/', views.order_edit, name='order_edit'),
        path('order/<int:pk>/delete/', views.order_delete, name='order_delete'),
        path('order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
        path('cart/detail', views.cart_detail, name='cart_detail'),
        path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

shopping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('maplegrocery.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/cart/detail.html
{% extends "maplegrocery/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
{#    <link href="{% static "css/cart.css" %}" rel="stylesheet"/>#}
    <style>
        img {
            width: 300px;
            object-fit: cover;
        }
    </style>
    <h1>Your shopping cart</h1>
    <section class="py-3 center">
        <div class="table-responsive">
            <table class="table table-striped table-hover table-fixed w-auto">
                <thead>
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit price</th>
                    <th>Price</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %}{{ product.image.url}}{% else %}{% static "images/no_preview.jpg" %}{% endif %}" alt="product-image">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "maplegrocery:cart_add" product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" class="btn btn-outline-dark" value="Update">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td>
                                <form action="{% url "maplegrocery:cart_remove" product.id %}"
                                      method="post">
                                    <input type="submit" class="btn btn-outline-dark" value="Remove">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td class="num">${{ item.price }}</td>
                            <td class="num">${{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="total">
                    <td>Total</td>
                    <td colspan="4"></td>
                    <td class="num">${{ cart.get_total_price }}</td>
                </tr>
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url "maplegrocery:product_list" %}" class="btn btn-outline-dark">Continue shopping</a>
                {% if cart.get_total_price > 0 %}
                    <a href="{% url "maplegrocery:order_create" %}" class="btn btn-outline-dark">Checkout</a>
                {% endif %}
            </p>
        </div>
    </section>
{% endblock %}