maplegrocery/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'maplegrocery'

urlpatterns = [
        path('', views.product_list, name='product_list'),
        # re_path(r'^home/$', views.home, name='home'),
        path('unit_list', views.unit_list, name='unit_list'),
        path('unit/create/', views.unit_new, name='unit_new'),
        path('unit/<int:pk>/edit/', views.unit_edit, name='unit_edit'),
        path('unit/<int:pk>/delete/', views.unit_delete, name='unit_delete'),
        path('product_list', views.product_list, name='product_list'),
        path('product_detail', views.product_detail, name='product_detail'),
        path('product/create/', views.product_new, name='product_new'),
        path('product/<int:pk>/edit/', views.product_edit, name='product_edit'),
        path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
        path('category_list', views.category_list, name='category_list'),
        path('category/create/', views.category_new, name='category_new'),
        path('category/<int:pk>/edit/', views.category_edit, name='category_edit'),
        path('category/<int:pk>/delete/', views.category_delete, name='category_delete'),
        path('order_list', views.order_list, name='order_list'),
        path('order/create/', views.order_create, name='order_create'),
        path('order/<int:pk>/edit/', views.order_edit, name='order_edit'),
        path('order/<int:pk>/delete/', views.order_delete, name='order_delete'),
        path('order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
        path('cart/detail', views.cart_detail, name='cart_detail'),
        path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
        path('cart/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

shopping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls', namespace='payment')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('maplegrocery.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

maplegrocery/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse



class Unit(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=280, null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.name}'


class Category(models.Model):
    name = models.CharField(max_length=50)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.name}'

    # def get_absolute_url(self):
    #     return reverse('maplegrocery:product_list_by_category',
    #                    args=[self.name])


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=280, null=True, blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    product_unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return f'{self.name}'


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    braintree_id = models.CharField(max_length=150, blank=True)
    preferred_date = models.DateField('Date')
    preferred_time = models.TimeField('Time')
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return f'{self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

maplegrocery/forms.py
from django import forms
from .models import Unit, Product, Category, Order, OrderItem
from django.forms.widgets import DateInput


class UnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ('name', 'description')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'price', 'available', 'product_unit', 'product_category')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address', 'postal_code', 'city', 'preferred_date', 'preferred_time')
        # Reference: https: // stackoverflow.com / questions / 3367091 / whats - the - cleanest - simplest - to - get - running - datepicker - in -django
        # https: // stackoverflow.com / questions / 55404397 / how - to - use - timeinput - widget - in -django - forms
        widgets = {'preferred_date': DateInput(attrs={'type': 'date'}),
                   'preferred_time': forms.TimeInput(attrs={'type': 'time'})}


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ('order', 'product', 'price', 'quantity', 'created_date')


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

maplegrocery/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail

from .cart import Cart
from .models import *
from .forms import *
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST

now = timezone.now()


def unit_list(request):
    unit = Unit.objects.filter(created_date__lte=timezone.now())
    return render(request, 'maplegrocery/unit_list.html',
                  {'units': unit})


@login_required
def unit_new(request):
    if request.method == "POST":
        form = UnitForm(request.POST)
        if form.is_valid():
            unit = form.save(commit=False)
            unit.created_date = timezone.now()
            unit.save()
            return redirect('maplegrocery:unit_list')
    else:
        form = UnitForm()
        # print("Else")
    return render(request, 'maplegrocery/unit_new.html', {'form': form})


@login_required
def unit_edit(request, pk):
    unit = get_object_or_404(Unit, pk=pk)
    if request.method == "POST":
        # update
        form = UnitForm(request.POST, instance=unit)
        if form.is_valid():
            unit = form.save(commit=False)
            unit.updated_date = timezone.now()
            unit.save()
            return redirect('maplegrocery:unit_list')
    else:
        # edit
        form = UnitForm(instance=unit)
    return render(request, 'maplegrocery/unit_edit.html', {'form': form})


@login_required
def unit_delete(request, pk):
    unit = get_object_or_404(Unit, pk=pk)
    unit.delete()
    return redirect('maplegrocery:unit_list')


def product_list(request):
    products = []
    if request.method == "GET":
        query = request.GET.get('search')
        print(query)
        if query == '' or query is None:
            query = 'None'
            products = Product.objects.filter(created_date__lte=timezone.now())
        else:
            products = Product.objects.filter(name__icontains=query)
    cart_product_form = CartAddProductForm()
    return render(request, 'maplegrocery/product_list.html',
                  {'products': products,
                   'cart_product_form': cart_product_form,
                   'query': query})

@login_required
def product_detail(request):
    product = Product.objects.filter(created_date__lte=timezone.now())
    return render(request, 'maplegrocery/product_detail.html',
                  {'products': product})


@login_required
def product_new(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            return redirect('maplegrocery:product_list')
    else:
        form = ProductForm()
        # print("Else")
    return render(request, 'maplegrocery/product_new.html', {'form': form})


@login_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        # update
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.updated_date = timezone.now()
            product.save()
            return redirect('maplegrocery:product_detail')
    else:
        # edit
        form = ProductForm(instance=product)
    return render(request, 'maplegrocery/product_edit.html', {'form': form})


@login_required
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect('maplegrocery:product_detail')


def category_list(request):
    category = Category.objects.filter(created_date__lte=timezone.now())
    return render(request, 'maplegrocery/category_list.html',
                  {'categorys': category})


@login_required
def category_new(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_date = timezone.now()
            category.save()
            return redirect('maplegrocery:category_list')
    else:
        form = CategoryForm()
    return render(request, 'maplegrocery/category_new.html', {'form': form})


@login_required
def category_edit(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        # update
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.updated_date = timezone.now()
            category.save()
            return redirect('maplegrocery:category_list')
    else:
        # edit
        form = CategoryForm(instance=category)
    return render(request, 'maplegrocery/category_edit.html', {'form': form})


@login_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect('maplegrocery:category_list')


def order_list(request):
    order = Order.objects.filter(created_date__lte=timezone.now())
    return render(request, 'maplegrocery/order_list.html',
                  {'orders': order})


def order_created(order_id):
    order = Order.objects.get(id=order_id)
    subject = f'Order nr. {order.id}'
    message = f'Dear {order.first_name},\n\n' \
              f'You have successfully placed an order.' \
              f'Your order ID is {order.id}.'
    mail_sent = send_mail(subject,
                          message,
                          settings.EMAIL_MAPLE,
                          [order.email])
    return mail_sent


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            order_created(order.id)
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))
    else:
        form = OrderForm()
    return render(request, 'orders/create.html', {'cart': cart, 'form': form})


@login_required
def order_edit(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if request.method == "POST":
        # update
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save(commit=False)
            order.updated_date = timezone.now()
            order.save()
            return redirect('maplegrocery:order_list')
    else:
        # edit
        form = OrderForm(instance=order)
    return render(request, 'maplegrocery/order_edit.html', {'form': form})


@login_required
def order_delete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    return redirect('maplegrocery:order_list')


@staff_member_required
# @login_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(settings.STATIC_FILES + '/css/pdf.css')])
    return response


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
    cart.add(product=product,
         quantity=cd['quantity'],
         override_quantity=cd['override'])
    return redirect('maplegrocery:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('maplegrocery:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})

templates/maplegrocery/category_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ category.id }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="">Cancel</a>
    </form>
{% endblock %}
</html>

templates/maplegrocery/category_edit.html
<!DOCTYPE html>
{% extends 'maplegrocery/base.html' %}
<html lang="en">

{% block content %}
    <h1>Edit Category</h1>
    <form method="POST" class="category-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/category_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'maplegrocery/base.html' %}
{% block content %}
    <h1>Add a new category</h1>
    <form method="POST" class="category-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Save</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/order_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ order.id }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="">Cancel</a>
    </form>
{% endblock %}
</html>

templates/maplegrocery/order_edit.html
<!DOCTYPE html>
{% extends 'maplegrocery/base.html' %}
<html lang="en">

{% block content %}
    <h1>Edit Order</h1>
    <form method="POST" class="order-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/order_list.html
<!DOCTYPE html>
{% extends 'maplegrocery/base.html' %}
{% block content %}
    <h1 style="padding-left: -40px; font-weight: bold; margin-top:10px">Order Details</h1>
    <section class="py-3">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Postal Code</th>
                    <th>Preferred Date</th>
                    <th>Preferred Time</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th>Paid</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.first_name }}</td>
                        <td>{{ order.last_name }}</td>
                        <td>{{ order.email }}</td>
                        <td>{{ order.address }}</td>
                        <td>{{ order.city }}</td>
                        <td>{{ order.postal_code }}</td>
                        <td>{{ order.preferred_date }}</td>
                        <td>{{ order.preferred_time }}</td>
                        <td>{{ order.created_date }}</td>
                        <td>{{ order.updated_date }}</td>
                        <td>{{ order.paid }}</td>
                        <td><a href="{% url 'maplegrocery:order_edit' pk=order.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'maplegrocery:order_delete' pk=order.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/maplegrocery/order_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'maplegrocery/base.html' %}
{% block content %}
    <h1>Add a new order</h1>
    <form method="POST" class="order-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Save</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/product_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ product.id }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="">Cancel</a>
    </form>
{% endblock %}
</html>

templates/maplegrocery/product_detail.html
{% extends 'maplegrocery/base.html' %}
{% load static %}
{% block content %}
    <style>
        img {
            width: 300px;
            object-fit: cover;
        }
    </style>
    <h1 style="padding-left: -40px; font-weight: bold; margin-top:10px">Product Details</h1>
    <a href="{% url 'maplegrocery:product_new' %}" class="btn btn-outline-dark"
       role="button">Add Product</a>
    <section class="py-3">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Price</th>
                    <th>Available</th>
                    <th>Unit</th>
                    <th>Category</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for product in products %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <th>{{ product.description }}</th>
                        <td><a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.image %}{{ product.image.url }}{% else %}{% static "images/no_preview.jpg" %}{% endif %}"
                                 alt="product-image" , width=150px; height=150px;">
                        </a></td>
                        <td>${{ product.price }}</td>
                        <td>{{ product.available }}</td>
                        <td>{{ product.product_unit }}</td>
                        <td>{{ product.product_category }}</td>
                        <td>{{ product.created_date }}</td>
                        <td>{{ product.updated_date }}</td>
                        <td><a href="{% url 'maplegrocery:product_edit' pk=product.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'maplegrocery:product_delete' pk=product.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}

templates/maplegrocery/product_edit.html
<!DOCTYPE html>
{% extends 'maplegrocery/base.html' %}
<html lang="en">

{% block content %}
    <h1>Edit Product</h1>
    <form method="POST" enctype="multipart/form-data" class="product-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/product_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'maplegrocery/base.html' %}
{% block content %}
    <h1>Add a new product</h1>
    <form method="POST" class="unit-form" enctype='multipart/form-data'>{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Save</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/unit_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ unit.id }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="">Cancel</a>
    </form>
{% endblock %}
</html>

templates/maplegrocery/unit_edit.html
<!DOCTYPE html>
{% extends 'maplegrocery/base.html' %}
<html lang="en">

{% block content %}
    <h1>Edit Unit</h1>
    <form method="POST" class="unit-form">{% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit" class="btn btn-outline-dark">Update</button>
    </form>
{% endblock %}
</html>

templates/maplegrocery/unit_list.html
{% extends 'maplegrocery/base.html' %}
{% block content %}
    <h1 style="padding-left: -40px; font-weight: bold; margin-top:10px">Unit Details</h1>
    <a href="{% url 'maplegrocery:unit_new' %}" class="btn btn-outline-dark" role="button">Add Unit</a>
    <section class="py-3">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Created Date</th>
                    <th>Updated Date</th>
                    <th colspan="3">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for unit in units %}
                    <tr>
                        <td>{{ unit.name }}</td>
                        <td>{{ unit.description }}</td>
                        <td>{{ unit.created_date }}</td>
                        <td>{{ unit.updated_date }}</td>
                        <td><a href="{% url 'maplegrocery:unit_edit' pk=unit.pk %}"
                               class="btn btn-warning">Edit</a></td>
                        <td><a href="{% url 'maplegrocery:unit_delete' pk=unit.pk %}"
                               onclick="return confirm('Are you sure you want to delete?')"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}